### PR TITLE
Implemented lightmode/darkmode functionality

### PR DESCRIPTION
**Pull request by vaibhav-1508**
Implemented dark mode/light mode functionality using material UI as mentioned in the following issue:https://github.com/FidalMathew/Poke-dex/issues/9

### CODE REVIEW

**Comment by FidalMathew** [comment]
@vaibhav-1508  Could you deploy the forked website using Vercel or other hosting platforms and share the link?

**Comment by FidalMathew** [comment]
@vaibhav-1508?

**Comment by vaibhav-1508** [comment]
> @vaibhav-1508?

sorry but vercel along with some of the GitHub functionality seems to be down for me at this time

**Comment by FidalMathew** [comment]
Ok @vaibhav-1508, could you send me a screenshot or video??

**Comment by vaibhav-1508** [comment]
Here are the screenshots:
image
image

**Comment by vaibhav-1508** [comment]
@FidalMathew is this fine?

**Comment by FidalMathew** [comment]
@vaibhav-1508 The navbar is not looking good with the design. Could you change the position of the switch below the search button? And apart from changing the background color. Could you also change the inner colors, and try out some combinations? 

Let me know which you like, and then you can work on it

**Comment by vaibhav-1508** [comment]
I removed the Navbar. I'm still learning react and I'm not yet proficient enough to implement the other features

**Comment by vaibhav-1508** [comment]
image
image
@FidalMathew

**Comment by vaibhav-1508** [comment]
@FidalMathew ?😅

**Comment by FidalMathew** [comment]
It looks off. Sorry @vaibhav-1508, I feel it would ruin the design if we add this to the website.😔

**Comment by vaibhav-1508** [comment]
> It looks off. Sorry @vaibhav-1508, I feel it would ruin the design if we add this to the website.😔

Okay, no problem 🚀

**Comment by FidalMathew** [comment]
Thank you for your efforts! 🚀

**Pull request closed without merging**
